#name: Publish version
#
#on:
#  workflow_dispatch:
#jobs:
#  testflight:
#    name: Publish libraries
#    runs-on: [macos-12]
#    timeout-minutes: 90
#    env:
#      MYUSER: ${{ secrets.USERNAME }}
#      MYPAT: ${{ secrets.PASSWORD }}
#      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
#    if: github.ref == 'refs/heads/master'
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#      - name: Github credentials
#        uses: extractions/netrc@v1
#        with:
#          machine: github.com
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#
#      - name: Github config
#        run: |
#            git config --global user.name "Dzertak"
#            git config --global user.email "kraftchenko.io@gmail.com"
#            git checkout -b master
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Publish version
#        run:  ./gradlew publishPlatforms
